language: c

git:
  depth: 50

branches:
  except:
  - freebsd

matrix:
  include:
    - name: "x64, linux, gcc 4.4, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.4
      env:
         - MATRIX_EVAL="CC=gcc-4.4 && CXX=g++-4.4"

    - name: "x64, linux, gcc 4.6, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.6
      env:
         - MATRIX_EVAL="CC=gcc-4.6 && CXX=g++-4.6"

    - name: "x64, linux, gcc 4.7, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env:
         - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"

    - name: "x64, linux, gcc 4.8.2, CMake 3.9.2"
      os: linux
      dist: trusty
      compiler: gcc

    - name: "x64, linux, gcc 4.9, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - name: "x64, linux, gcc 5, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - name: "x64, linux, gcc 6, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - name: "x64, linux, gcc 7, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: "x64, linux, gcc 7.4.0, CMake 3.12.4"
      os: linux
      dist: bionic
      compiler: gcc



    - name: "x64, linux, clang 3.5, CMake 3.9.2"
      os: linux
      dist: trusty
      compiler: clang

    - name: "x64, linux, clang 3.6, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - name: "x64, linux, clang 3.7, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

    - name: "x64, linux, clang 3.8, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - name: "x64, linux, clang 3.9, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - name: "x64, linux, clang 4.0, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - name: "x64, linux, clang 5.0, CMake 3.9.2"
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - name: "x64, linux, clang 7, CMake 3.12.4"
      os: linux
      dist: xenial
      compiler: clang



    - name: "x64, macOs, Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)"
      os: osx
      osx_image: xcode6.4

    - name: "x64, macOs, Apple LLVM version 9.1.0 (clang-902.0.39.2)"
      os: osx
      osx_image: xcode9.4

    - name: "x64, macOs, Apple LLVM version 10.0.0 (clang-1000.11.45.5)"
      os: osx
      osx_image: xcode10.1

    - name: "x64, macOs, Apple LLVM version 10.0.1 (clang-1001.0.46.3)"
      os: osx
      osx_image: xcode10.2

    - name: "x64, macOs, Apple LLVM version 10.0.1 (clang-1001.0.46.4)"
      os: osx
      osx_image: xcode10.3

    - name: "x64, macOs, Apple clang version 11.0.0 (clang-1100.0.33.8)"
      os: osx
      osx_image: xcode11



    - name: "x64, macOs, gcc 4.9"
      os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - name: "x64, macOs, gcc 5"
      os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    - name: "x64, macOs, gcc 6"
      os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    - name: "x64, macOs, gcc 7"
      os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=./install ..
  - make
